[package]
name = "kafka_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
futures = { version = "0.3.21", default-features = false }
governor = { version = "0.4.2", default-features = false, features = ["dashmap", "jitter", "std"] }
rdkafka = { version = "0.28.0", default-features = false, features = ["tokio", "zstd", "libz"] }
tokio = { version = "1.19.2", features = ["rt-multi-thread", "macros"] }