version: 2
updates:
    - package-ecosystem: cargo
      directory: /
      schedule:
        interval: daily
        time: "04:00" # UTC
      labels:
        - "deps"
      commit-message:
        prefix: "chore(deps)"
