[build.env]
passthrough = [
    "BUILD_DIR",
    "CARGO_PROFILE_RELEASE_OPT_LEVEL",
    "CARGO_PROFILE_RELEASE_CODEGEN_UNITS",
    "RUST_BACKTRACE",
    "RUST_LOG",
    "VERTEX_BUILD_DESC",
]

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/f1shl3gs/vertex-builder:x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-musl]
image = "ghcr.io/f1shl3gs/vertex-builder:x86_64-unknown-linux-musl"
