global:
  data_dir: ./temp

health_checks:
  enabled: false

extensions: {}
  # pprof:
  #   type: pprof
  #   listen: 127.0.0.1:9000
  # jemalloc:
  #   type: jemalloc

sources:
  internal_metrics:
    type: internal_metrics
    interval: 15s
  selfstat:
    type: selfstat
  internal_logs:
    type: internal_logs
  libvirt:
    type: libvirt

transforms:
  add_extra_tags:
    type: add_tags
    inputs:
      - internal_logs
    tags:
      hostname: ${HOSTNAME}

sinks:
  prom:
    type: prometheus_exporter
    inputs:
      - add_extra_tags
      - selfstat
      - internal_metrics
      - libvirt
    listen: 127.0.0.1:9101