global:
  runtime:
    worker: 4

health_checks:
  enabled: false

sources:
  node:
    type: generator

transforms:
  add_extra_tags:
    type: add_tags
    inputs:
      - node
    tags:
      hostname: ${HOSTNAME}

sinks:
  stdout:
    type: stdout
    inputs:
      - add_extra_tags
