global:
  data_dir: ./temp

health_checks:
  enabled: false

extensions:
  healthcheck:
    type: healthcheck
  pprof:
    type: pprof
    listen: 127.0.0.1:9000
  # jemalloc:
  #   type: jemalloc

sources:
  internal_metrics:
    type: internal_metrics
    interval: 15s
  selfstat:
    type: selfstat
  internal_logs:
    type: internal_logs
  dummy:
    type: prometheus_scrape
    endpoints:
      - http://127.0.0.1:9100/metrics
  tail:
    type: tail
    include:
      - "/home/f1shl3gs/Workspaces/clion/vertex/tmp.txt"
  prw:
    type: prometheus_remote_write

transforms:
  add_extra_tags:
    type: add_tags
    inputs:
      - internal_logs
    tags:
      hostname: ${HOSTNAME}

sinks:
  prom:
    type: prometheus_exporter
    inputs:
      - add_extra_tags
      - selfstat
      - internal_metrics
    listen: 127.0.0.1:9101
  stdout:
    type: stdout
    inputs:
      - tail