global:
  data_dir: ./temp

health_checks:
  enabled: false

extensions: {}
  # pprof:
  #   type: pprof
  #   listen: 127.0.0.1:9000
  # jemalloc:
  #   type: jemalloc

sources:
  tail:
    type: tail
    include:
      - "/home/f1shl3gs/Workspaces/clion/vertex/*.toml"

transforms: {}

sinks:
  stdout:
    type: stdout
    inputs:
      - tail