global:
  runtime:
    worker: 4

health_checks:
  enabled: false

sources:
  kmsg:
    type: kmsg
  node:
    type: node_metrics
    interval: 15s
  selfstat:
    type: selfstat
  generator:
    type: generator
  ntp:
    type: ntp
    interval: 15s
    timeout: 10s
    pools:
      - time1.aliyun.com
      - time2.aliyun.com
      - time3.aliyun.com
      - time4.aliyun.com
      - time5.aliyun.com
      - time6.aliyun.com
      - time7.aliyun.com

transforms:
  add_extra_tags:
    type: add_tags
    inputs:
      - generator
      - ntp
    tags:
      hostname: ${HOSTNAME}

sinks:
  stdout:
    type: stdout
    inputs:
      - kmsg
  prom:
    type: prometheus_exporter
    inputs:
      - add_extra_tags
      - node
      - selfstat
    listen: 127.0.0.1:9101
