global:
  data_dir: ./temp

health_checks:
  enabled: false

extensions: {}
  # pprof:
  #   type: pprof
  #   listen: 127.0.0.1:9000
  # jemalloc:
  #   type: jemalloc

sources:
  tail:
    type: tail
    line_delimiter: "\n"
    include:
      - "/home/f1shl3gs/Workspaces/clion/vertex/tmp.txt"
  selfstat:
    type: selfstat

transforms: {}

sinks:
  stdout:
    type: stdout
    inputs:
      - tail
  prom:
    type: prometheus_exporter
    inputs:
      - selfstat