global:
  runtime:
    worker: 4

health_checks:
  enabled: false

sources:
  generator:
    type: generator

transforms:
  add_extra_tags:
    type: add_tags
    inputs:
      - generator
    tags:
      hostname: ${HOSTNAME}

sinks:
  stdout:
    type: stdout
    inputs:
      - add_extra_tags
  prom:
    type: prometheus_exporter
    inputs:
      - add_extra_tags
