services:
  vertex:
    image: vertex:regression
    ports:
      - 9100:9100 # prometheus exporter
      - 9091:9091 # pprof
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 1G
    volumes:
      - ${PWD}/vertex.yaml:/etc/vertex/vertex.yaml
      - data:/data

  lading:
    image: ghcr.io/datadog/lading:0.25.4
    depends_on:
      - vertex
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 4G # prebuild cache could be very large
    ports:
      - 9101:9101
    volumes:
      - ${PWD}/lading.yaml:/lading.yaml:ro
      - data:/data
    command:
      - --config-path
      - /lading.yaml
      - --prometheus-addr
      - 0.0.0.0:9101
      - --no-target
      - --experiment-duration-seconds
      - "600"
      - --warmup-duration-seconds
      - "5"

volumes:
  data:
    driver_opts:
      type: tmpfs
      device: tmpfs
