apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: monitoring
    includeSelectors: true
    includeTemplates: true

resources:
  - rbac.yaml
  - serviceaccount.yaml
  - loki.yaml
  - vertex.yaml
  - grafana.yaml
  - prometheus.yaml