apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: vertex
      app.kubernetes.io/instance: vertex
      app.kubernetes.io/component: Agent
    includeSelectors: true
    includeTemplates: true

resources:
  - configmap.yaml
  - daemonset.yaml
  - rbac.yaml
  - serviceaccount.yaml
  - service-headless.yaml
