apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vertex
rules:
  - verbs:
      - list
      - watch
    apiGroups:
      - ""
    resources:
      - namespaces
      - nodes
      - pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vertex
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vertex
subjects:
  - kind: ServiceAccount
    name: vertex
    namespace: default
