global:
  data_dir: ./temp

health_checks:
  enabled: false

provider:
  type: http
  url: http://localhost:8100/config
  interval: 10s

sources:
  internal:
    type: internal_logs

sinks:
  stdout:
    type: console
    inputs:
      - internal
    encoding:
      codec: json