[package]
name = "fake_node_exporter"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.21.0", features = ["macros", "rt-multi-thread"] }
hyper = { version = "0.14.20", features = ["server", "tcp", "http1"] }