name: Baseline Timings

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *" # every 12 hour

env:
  CI: true

jobs:
  release-build-optimized:
    name: "Release Build (optimized)"
    runs-on: [self-hosted, linux, x64, general]
    steps:
      - uses: actions/checkout@v2.4.0
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: cargo clean
      - run: cargo build --release

  release-build-normal:
    name: "Release Build (normal)"
    runs-on: [self-hosted, linux, x64, general]
    env:
      # We're not actually doing a debug build, we're just turning off the logic
      # in release-flags.sh so that we don't override the Cargo "release" profile
      # with full LTO / single codegen unit.
      PROFILE: debug
    steps:
      - uses: actions/checkout@v2.4.0
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: cargo clean
      - run: cargo build --release

  debug-build:
    name: "Debug Build"
    runs-on: [self-hosted, linux, x64, general]
    steps:
      - uses: actions/checkout@v2.4.0
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: cargo clean
      - run: cargo build

  debug-rebuild:
    name: "Debug Rebuild"
    runs-on: [self-hosted, linux, x64, general]
    steps:
      - uses: actions/checkout@v2.4.0
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: cargo clean
      - run: cargo build
      - run: touch src/app.rs
      - run: cargo build

  check:
    name: "Cargo Check"
    runs-on: [self-hosted, linux, x64, general]
    steps:
      - uses: actions/checkout@v2.4.0
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: cargo clean
      - run: cargo check
