name: Pull Request Labler

on:
  - pull_request_target

jobs:
  label:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/labeler@v6
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
